name: Release

on:
  push:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Log in to the container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build container image
        run: IMG_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} make docker-build

      - name: Push container image
        run: IMG_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} make docker-push
